### ISSUE TITLE
Dependency conflict

### ISSUE THREAD

**Issue by peterjhart** [sitepoint-editors/angular-js-unit-testing-services-controllers-providers#2]
Latest versions of one/some/all dependencies break the build.

When I changed the semantics in my local package.json from "^" to "=" and everything worked.

Thanks for the repo!

**Comment by jameshibbard** [comment]
Thanks for pointing that out :)

I tested it and indeed it is broken. The error I'm getting is:

```
Error: [$injector:modulerr] Failed to instantiate module ng due to:
TypeError: 'undefined' is not an object (evaluating 'Function.prototype.bind.apply')
```

Apparently, this is because Phantom 1.x doesn't have `Function.prototype.bind`. Instead you can use Phantom 2.x or a [polyfill](https://github.com/conversocial/phantomjs-polyfill/blob/master/bind-polyfill.js).

More info: https://github.com/angular/angular.js/issues/13794

Alternatively, you can lock the versions in `package.json` (as you have done) and it works as expected. You don't need the equals sign, though. You can just specify the version number directly:

```
"angular-mocks": "1.3.15"
```

I've updated the repo accordingly.
